# Generated by Django 5.0.3 on 2024-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_sale', '0002_product_oum_productattributetype_productlot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(help_text="The category's code.", max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(help_text="The product's barcode.", max_length=20),
        ),
    ]
