# Generated by Django 5.0.3 on 2024-03-28 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_sale', '0003_alter_category_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
